import { Platform, StyleSheet } from "react-native";

export const color = {
  paper: "#f5f2e9",
  surface: "#fffcf6",
  ink: "#203d35",
  muted: "#647463",
  line: "#c9cfc2",
  primary: "#284e40",
  jev: "#6f52ed",
  danger: "#a54538",
};
export const font = Platform.OS === "ios" ? "Avenir Next" : "sans-serif";
export const palette = [
  "#ed4968",
  "#e35b00",
  "#b27c00",
  "#7e8f00",
  "#159b05",
  "#009969",
  "#00959c",
  "#008ecc",
  "#2c84ff",
  "#8672fd",
  "#bb5ede",
  "#dd51ad",
];
export const styles = StyleSheet.create({
  app: { flex: 1, backgroundColor: color.paper },
  row: { flexDirection: "row", alignItems: "center", gap: 8 },
  wrap: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  text: { fontFamily: font, color: color.ink, fontSize: 15, lineHeight: 22 },
  note: { fontFamily: font, color: color.muted, fontSize: 13, lineHeight: 19 },
  label: {
    fontFamily: font,
    color: color.muted,
    fontSize: 12,
    marginBottom: 6,
  },
  title: {
    fontFamily: "Georgia",
    color: color.ink,
    fontSize: 29,
    lineHeight: 34,
    letterSpacing: -1,
  },
  brand: {
    fontFamily: "Georgia",
    fontStyle: "italic",
    fontSize: 32,
    color: color.ink,
    letterSpacing: -1.5,
  },
  field: {
    fontFamily: font,
    color: color.ink,
    fontSize: 16,
    minHeight: 46,
    backgroundColor: color.surface,
    borderColor: color.line,
    borderWidth: 1,
    borderRadius: 6,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  multiline: { minHeight: 96, textAlignVertical: "top" },
  section: { gap: 12 },
  divider: {
    height: StyleSheet.hairlineWidth,
    backgroundColor: color.line,
    marginVertical: 8,
  },
  button: {
    minHeight: 44,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: color.line,
    borderRadius: 6,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: color.surface,
  },
  buttonText: { fontFamily: font, color: color.ink, fontSize: 14 },
  primary: { backgroundColor: color.primary, borderColor: color.primary },
  primaryText: { color: color.surface },
  chosen: { backgroundColor: "#e7ecdf", borderColor: "#829784" },
  quiet: { borderColor: "transparent", backgroundColor: "transparent" },
  disabled: { opacity: 0.4 },
  error: {
    color: color.danger,
    fontFamily: font,
    fontSize: 13,
    lineHeight: 20,
  },
});
